language: c

env:
    global:
        - _R_CHECK_TIMINGS_=0

warnings_are_errors: false

sudo: true

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap

install:
    - cd ./R-package
    - ../travis-tool.sh install_deps

script: 
    - bash ../travis-tool.sh run_tests  
    - bash cat /home/travis/build/dmlc/xgboost/R-package/xgboost.Rcheck/00install.out

after_failure: cat /home/travis/build/dmlc/xgboost/R-package/xgboost.Rcheck/00install.out

on_failure:
    - cat /home/travis/build/dmlc/xgboost/R-package/xgboost.Rcheck/00install.out
    - ../travis-tool.sh dump_logs
    
after_script: cat /home/travis/build/dmlc/xgboost/R-package/xgboost.Rcheck/00install.out

notifications:
    email:
        recipients:
            - hetong007@gmail.com
            - tqchen@cs.washington.edu
        on_success: change
        on_failure: always

